import GetLocationButton from '@components/GetLocationButton';
import Login from '@components/Login';
import { Metadata } from 'next';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/server/auth';
import Image from 'next/image';
import AdminPanelButton from './_components/AdminPanelButton';

export const metadata: Metadata = {
  title: 'Electric Rescue',
  description: 'Generated by create next app',
};
export default async function Home() {
  const session = await getServerSession(authOptions);
  return (
    <main className=" mx-10 mt-5">
      {/* <h1 className="prose text-center text-4xl">
        Welcome to{' '}
        <span className="prose text-4xl text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-green-500">
          Electric Rescue
        </span>
      </h1> */}
      <div className="flex flex-col items-center justify-center p-8">
        <Image src="/logo.jpeg" alt="logo" width={400} height={100}></Image>
        <Login />
        <GetLocationButton />
        <AdminPanelButton />
      </div>
    </main>
  );
}
